# SPDX-License-Identifier: GPL-2.0-only
obj-y	+= mm/ kernel/ math-emu/ net/

# for cleaning
subdir- += boot

subdir-ccflags-$(CONFIG_WNO_MISSING_PROTOTYPES) := -Wno-missing-prototypes -Wno-missing-declarations
