# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_TI_CPPI41) += cppi41.o
obj-$(CONFIG_TI_EDMA) += edma.o
omap-dma-ll-$(CONFIG_ARCH_OMAP) += omap-dma-lowlevel.o
obj-$(CONFIG_DMA_OMAP) += omap-dma.o $(omap-dma-ll-y)
obj-$(CONFIG_TI_DMA_CROSSBAR) += dma-crossbar.o
