#
# Makefile for ALSA
# Copyright (c) 2004 by Jaroslav Kysela <perex@perex.cz>
#

snd-pdaudiocf-objs := pdaudiocf.o pdaudiocf_core.o pdaudiocf_irq.o pdaudiocf_pcm.o
GCOV_PROFILE_pdaudiocf_irq.o := n

obj-$(CONFIG_SND_PDAUDIOCF) += snd-pdaudiocf.o
