# SPDX-License-Identifier: GPL-2.0-only

obj-y += kernel/ mm/ net/
obj-$(CONFIG_BUILTIN_DTB) += boot/dts/
obj-y += errata/
obj-$(CONFIG_KVM) += kvm/

obj-$(CONFIG_KEXEC_FILE) += purgatory/

# for cleaning
subdir- += boot
