# SPDX-License-Identifier: GPL-2.0
obj-y				+= mv78xx0-common.o mv78xx0-mpp.o mv78xx0-irq.o mv78xx0-pcie.o
obj-$(CONFIG_MACH_DB78X00_BP)	+= db78x00-bp-setup.o
obj-$(CONFIG_MACH_RD78X00_MASA)	+= rd78x00-masa-setup.o
obj-$(CONFIG_MACH_TERASTATION_WXL) += buffalo-wxl-setup.o
