
generic-y += clkdev.h
generic-y += exec.h
generic-y += ipcbuf.h
generic-y += irq_work.h
generic-y += kvm_para.h
generic-y += mcs_spinlock.h
generic-y += msgbuf.h
generic-y += preempt.h
generic-y += scatterlist.h
generic-y += sembuf.h
generic-y += shmbuf.h
generic-y += trace_clock.h
generic-y += vtime.h
