# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for Nios2-specific library files.
#
ccflags-$(CONFIG_WNO_MISSING_PROTOTYPES) := -Wno-missing-prototypes -Wno-missing-declarations

lib-y += delay.o
lib-y += memcpy.o
lib-y += memmove.o
lib-y += memset.o
