# SPDX-License-Identifier: GPL-2.0
kmsan-cflags := -fsanitize=kernel-memory
kmsan-cflags += $(call cc-option, -finline-max-stacksize=128)

ifdef CONFIG_KMSAN_CHECK_PARAM_RETVAL
kmsan-cflags += -fsanitize-memory-param-retval
endif

export CFLAGS_KMSAN := $(kmsan-cflags)
