# arch/arm/mach-s5pv210/Makefile
#
# Copyright (c) 2010 Samsung Electronics Co., Ltd.
# 		http://www.samsung.com/
#
# Licensed under GPLv2

ccflags-$(CONFIG_ARCH_MULTIPLATFORM) +=  -I$(srctree)/arch/arm/plat-samsung/include

obj-$(CONFIG_PM_SLEEP)		+= s5pv210-pm.o s5pv210-sleep.o

# machine support

obj-y				+= s5pv210.o
