# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Kernel-based Virtual Machine module
#

obj-$(CONFIG_KVM_COMMON) += kvm-core.o

kvm-core-y := $(KVM)/kvm_main.o $(KVM)/eventfd.o $(KVM)/binary_stats.o
kvm-core-$(CONFIG_KVM_VFIO) += $(KVM)/vfio.o
kvm-core-$(CONFIG_KVM_MMIO) += $(KVM)/coalesced_mmio.o
kvm-core-$(CONFIG_KVM_ASYNC_PF) += $(KVM)/async_pf.o
kvm-core-$(CONFIG_HAVE_KVM_IRQ_ROUTING) += $(KVM)/irqchip.o
kvm-core-$(CONFIG_HAVE_KVM_DIRTY_RING) += $(KVM)/dirty_ring.o
kvm-core-$(CONFIG_HAVE_KVM_PFNCACHE) += $(KVM)/pfncache.o
kvm-core-$(CONFIG_KVM_GUEST_MEMFD) += $(KVM)/guest_memfd.o
