# SPDX-License-Identifier: GPL-2.0-only

obj-y += kernel/ mm/ platform/ boot/dts/

# for cleaning
subdir- += boot

subdir-ccflags-$(CONFIG_WNO_MISSING_PROTOTYPES) := -Wno-missing-prototypes -Wno-missing-declarations
